export enum ActionTypeRegister {
  POST_REGISTER_PENDING = "POST_REGISTER_PENDING",
  POST_REGISTER_SUCCESS = "POST_REGISTER_SUCCESS",
  POST_REGISTER_FAILED = "POST_REGISTER_FAILED",
}

export enum ActionTypeLogin {
  POST_LOGIN_PENDING = "POST_LOGIN_PENDING",
  POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS",
  POST_LOGIN_FAILED = "POST_LOGIN_FAILED",
}

export enum ActionTypeOTP {
  POST_OTP_PENDING = "POST_OTP_PENDING",
  POST_OTP_SUCCESS = "POST_OTP_SUCCESS",
  POST_OTP_FAILED = "POST_OTP_FAILED",
}

export enum ActionTypeForgotPassword {
  POST_FORGOTPASSWORD_PENDING = "POST_FORGOTPASSWORD_PENDING",
  POST_FORGOTPASSWORD_SUCCESS = "POST_FORGOTPASSWORD_SUCCESS",
  POST_FORGOTPASSWORD_FAILED = "POST_FORGOTPASSWORD_FAILED",
}