export enum ActionType {
    FETCH_SEARCH_PENDING = "FETCH_SEARCH_PENDING",
    FETCH_SEARCH_SUCCESS = "FETCH_SEARCH_SUCCESS",
    FETCH_SEARCH_FAILED = "FETCH_SEARCH_FAILED",
    FETCH_LIST_HOTEL_PENDING = "FETCH_LIST_HOTEL_PENDING",
    FETCH_LIST_HOTEL_SUCCESS = "FETCH_LIST_HOTEL_SUCCESS",
    FETCH_LIST_HOTEL_FAILED = "FETCH_LIST_HOTEL_FAILED",
    ONCHANGE_INPUT = "ONCHANGE_INPUT",
    ONCHANGE_ADULT = "ONCHANGE_ADULT",
    ONCHANGE_CHILDREN = "ONCHANGE_CHILDREN",
    ONCHANGE_ROOM = "ONCHANGE_ROOM",
    ONCLICK_LIST_SEARCH = "ONCLICK_LIST_SEARCH"
}