export enum ActionType {
  GET_LIST_STATION_SUCCESS = "GET_LIST_STATION_SUCCESS",
  GET_LIST_STATION_PENDING = "GET_LIST_STATION_PENDING",
  GET_LIST_STATION_FAILED = "GET_LIST_STATION_FAILED"
}

export enum ActionTypeAvailability {
  POST_STATION_AVAILABILITY = 'POST_STATION_AVAILABILITY',
  POST_STATION_AVAILABILITY_LOADING = 'POST_STATION_AVAILABILITY_LOADING',
  POST_STATION_AVAILABILITY_FAILED = 'POST_STATION_AVAILABILITY_FAILED'
}