apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-services
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-services
  template:
    metadata:
      labels:
        app: frontend-services
    spec:
      containers:
      - name: frontend-services
        image: asia-southeast2-docker.pkg.dev/calm-suprstate-352907/caritempat/frontend-services:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: frontend-services
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: artifact-registry
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-services
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: frontend-services